Nodejs-Express application
commands to build and create.
To build image:"docker image build -t node1:16-alpine ." <name:version>
To Create container :"docker container run --name newjs -d -P 1a0288859300 =>"<image name/id>

trail-1
FROM node:16-alpine
LABEL author="Manu" organization="khaja.tec" project="nodejs"
RUN apk add --update npm && \
    apk add git && \
    git clone https://github.com/expressjs/express.git && \
    cd express && \
    npm install express && \
    npm install -g express-generator@4 && \
    express /tmp/foo && \
    cd /tmp/foo && \
    npm install
WORKDIR /tmp/foo
EXPOSE 3000
CMD ["npm","start"]

output :
![preview]

trail-2
FROM node:16-alpine
LABEL author="Manu" organization="khaja.tec" project="nodejs"
RUN apk add --update  && \
    apk add git && \
    git clone https://github.com/expressjs/express.git \
    && cd express && \
    npm install express && \
    npm install -g express-generator@4 && \
    express /tmp/foo && cd /tmp/foo && \
    npm install
WORKDIR /tmp/foo
EXPOSE 3000
CMD ["npm","start"]

FROM ubuntu:22.04
LABEL author="Manu" organization="khaja.tec" project="nodejs"
RUN apt update  && \
    apt install npm -y && \
    apt install git -y && \
    git clone https://github.com/expressjs/express.git \
    && cd express && \
    npm install express - && \
    npm install -g express-generator@4 && \
    express /tmp/foo && cd /tmp/foo && \
    npm install
WORKDIR /tmp/foo
EXPOSE 3000
CMD ["npm","start"]

FROM ubuntu:22.04
LABEL author="Manu" organization="khaja.tec" project="nodejs"
RUN apt update
RUN apt install npm -y
RUN apt install git -y
RUN git clone https://github.com/expressjs/express.git
WORKDIR /express
RUN  npm install express
RUN apt install npm -y
RUN npm install -g express-generator@4
RUN express /tmp/foo
WORKDIR /tmp/foo
RUN npm install
EXPOSE 3000
CMD ["npm","start"]

FROM node:slim
LABEL author="Manu" organization="khaja.tec" project="nodejs"
RUN apt update
RUN apt install npm -y
RUN apt install git -y
RUN git clone https://github.com/expressjs/express.git
WORKDIR /express
RUN  npm install express
RUN apt install npm -y
RUN npm install -g express-generator@4
RUN express /tmp/foo
WORKDIR /tmp/foo
RUN npm install
EXPOSE 3000
ENTRYPOINT ["npm","start"]


## working
FROM node:16-alpine
RUN apk add --update
RUN apk add git
RUN git clone https://github.com/expressjs/express.git
RUN cd express
WORKDIR /express
RUN npm install express
RUN npm install -g express-generator@4
RUN express /tmp/foo
WORKDIR /tmp/foo
RUN npm install
EXPOSE 3000
CMD ["npm", "start"]

## working
FROM node:16-alpine
RUN apk add --update
RUN apk add git
RUN git clone https://github.com/expressjs/express.git
RUN cd express && \
    npm install express && \
    npm install -g express-generator@4 && \
    express /tmp/foo
WORKDIR /tmp/foo
RUN npm install
EXPOSE 3000
CMD ["npm", "start"]




